name: ubuntu 20.04

on:
  repository_dispatch:
  #   release:
  #     types: published
  #   push:
  #     branches:
  #       - main
  #     paths:
  #       - 'newifiD2.config'
  #  schedule:
  #    - cron: 0 8 * * 5
  watch:
    types: started

env:
  REPO_URL: https://github.com/beiyuqu/miui-rom.git
  REPO_BRANCH: master
  SSH_ACTIONS: false
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_COWTRANSFER: false
  UPLOAD_WETRANSFER: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: init system
        run: |
          sudo apt update && sudo apt upgrade -y

      - name: Clone source code
        run: |
          git clone $REPO_URL

      - name: SSH connection to Actions
        uses: P3TERX/ssh2actions@v1.0.0
        if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
        env:
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
